### ISSUE TITLE
Добавить в listProduct пометку товар в наличии!!! или хотя бы подумать об этом))

### ISSUE THREAD

**Issue by artemzalescky** [artemzalescky/electrika#11]

**Comment by aminzer** [comment]
в админке можно убрать флажок в наличии, сохранить
проверить на сайте

**Comment by artemzalescky** [comment]
неее...что товар есть в наличии я считаю это важно

**Comment by aminzer** [comment]
если в админке выставляешь, что товара нет в наличии, то в listProducts пишется, что его нет
